"""Simple civilian provider presets for JobMatch scoring."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ProviderPreset:
    name: str
    base_url: str
    model: str
    key_prompt: str
    key_url: str


SIMPLE_PROVIDERS: dict[str, ProviderPreset] = {
    "deepseek": ProviderPreset(
        name="deepseek",
        base_url="https://api.deepseek.com/v1",
        model="deepseek-chat",
        key_prompt="DeepSeek API key",
        key_url="https://platform.deepseek.com/api_keys",
    ),
    "openai": ProviderPreset(
        name="openai",
        base_url="https://api.openai.com/v1",
        model="gpt-4o-mini",
        key_prompt="OpenAI API key",
        key_url="https://platform.openai.com/api-keys",
    ),
    "openrouter": ProviderPreset(
        name="openrouter",
        base_url="https://openrouter.ai/api/v1",
        model="openai/gpt-4o-mini",
        key_prompt="OpenRouter API key",
        key_url="https://openrouter.ai/keys",
    ),
    "groq": ProviderPreset(
        name="groq",
        base_url="https://api.groq.com/openai/v1",
        model="llama-3.1-8b-instant",
        key_prompt="Groq API key",
        key_url="https://console.groq.com/keys",
    ),
}

SIMPLE_PROVIDER_CHOICES = tuple(SIMPLE_PROVIDERS)


def render_llm_env(
    *,
    base_url: str,
    api_key: str,
    model: str,
    notifier: str = "console",
) -> str:
    """Render a ~/.jobmatch/.env body. Never log the api_key."""
    return "\n".join(
        [
            "# JobMatch private secrets",
            "# Generated by jobmatch init. Do not commit this file.",
            "",
            f"JOBMATCH_LLM_BASE_URL={base_url.rstrip('/')}",
            f"JOBMATCH_LLM_API_KEY={api_key}",
            f"JOBMATCH_LLM_MODEL={model}",
            "",
            f"JOBMATCH_NOTIFIER={notifier}",
            "",
        ]
    )
